### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by articfrez** [devyndamonster/MagazinePatcher#1]
While loading it stops at 27% and crashes.

**Comment by articfrez** [comment]
I barely have anytime to read the console but it says that it failed reading the cache.

**Comment by RavenLunaris** [comment]
have similar issue. massive mem leak leads to access violation crash.

**Comment by devyndamonster** [comment]
Can both of you send your bepinex log files here?

**Comment by articfrez** [comment]
After uninstalling a few mods that I assume caused problems, this is the log file.
[LogOutput.log](https://github.com/devyndamonster/MagazinePatcher/files/7356159/LogOutput.log)

**Comment by RavenLunaris** [comment]
I was able to solve my issue.. actually not sure it's memory leak anymore, might just be the mods just got bigger or some screwy stuff with windows
